export type Category = "Emocional" | "Cognitivo" | "Social" | "Comportamental" | "Valores";

export type AdjectiveItem = {
  label: string;
  category: Category;
};

export const CATEGORIES: Category[] = [
  "Emocional",
  "Cognitivo",
  "Social",
  "Comportamental",
  "Valores",
];

export const CATEGORY_ICONS: Record<Category, string> = {
  Emocional: "heart",
  Cognitivo: "cpu",
  Social: "users",
  Comportamental: "activity",
  Valores: "star",
};

export const CATEGORY_COLORS: Record<Category, { bg: string; text: string; active: string }> = {
  Emocional: { bg: "#FEF2F2", text: "#991B1B", active: "#DC2626" },
  Cognitivo: { bg: "#EFF6FF", text: "#1D4ED8", active: "#2563EB" },
  Social: { bg: "#F0FDF4", text: "#166534", active: "#16A34A" },
  Comportamental: { bg: "#FFF7ED", text: "#9A3412", active: "#EA580C" },
  Valores: { bg: "#FAF5FF", text: "#6B21A8", active: "#9333EA" },
};

export const CURRENT_ADJECTIVES: AdjectiveItem[] = [
  // Emocional
  { label: "ansioso", category: "Emocional" },
  { label: "tenso", category: "Emocional" },
  { label: "triste", category: "Emocional" },
  { label: "irritável", category: "Emocional" },
  { label: "vazio", category: "Emocional" },
  { label: "inseguro", category: "Emocional" },
  { label: "culpado", category: "Emocional" },
  { label: "ressentido", category: "Emocional" },
  { label: "sobrecarregado", category: "Emocional" },
  { label: "volátil", category: "Emocional" },
  { label: "melancólico", category: "Emocional" },
  { label: "frágil", category: "Emocional" },
  // Cognitivo
  { label: "pessimista", category: "Cognitivo" },
  { label: "autocrítico", category: "Cognitivo" },
  { label: "perfeccionista", category: "Cognitivo" },
  { label: "rígido", category: "Cognitivo" },
  { label: "distraído", category: "Cognitivo" },
  { label: "indeciso", category: "Cognitivo" },
  { label: "catastrofizante", category: "Cognitivo" },
  { label: "confuso", category: "Cognitivo" },
  { label: "comparativo", category: "Cognitivo" },
  { label: "limitado", category: "Cognitivo" },
  { label: "ruminante", category: "Cognitivo" },
  { label: "impulsivo", category: "Cognitivo" },
  // Social
  { label: "tímido", category: "Social" },
  { label: "solitário", category: "Social" },
  { label: "fechado", category: "Social" },
  { label: "dependente", category: "Social" },
  { label: "submisso", category: "Social" },
  { label: "desconfiante", category: "Social" },
  { label: "distante", category: "Social" },
  { label: "controlador", category: "Social" },
  { label: "ciumento", category: "Social" },
  { label: "retraído", category: "Social" },
  { label: "agressivo", category: "Social" },
  { label: "evitativo", category: "Social" },
  // Comportamental
  { label: "procrastinador", category: "Comportamental" },
  { label: "agitado", category: "Comportamental" },
  { label: "passivo", category: "Comportamental" },
  { label: "conformado", category: "Comportamental" },
  { label: "desmotivado", category: "Comportamental" },
  { label: "acelerado", category: "Comportamental" },
  { label: "desorganizado", category: "Comportamental" },
  { label: "impulsivo", category: "Comportamental" },
  { label: "negligente", category: "Comportamental" },
  { label: "reativo", category: "Comportamental" },
  { label: "evitativo", category: "Comportamental" },
  { label: "dependente", category: "Comportamental" },
  // Valores
  { label: "perdido", category: "Valores" },
  { label: "sem propósito", category: "Valores" },
  { label: "superficial", category: "Valores" },
  { label: "materialista", category: "Valores" },
  { label: "ingrato", category: "Valores" },
  { label: "egoísta", category: "Valores" },
  { label: "inflexível", category: "Valores" },
  { label: "desengajado", category: "Valores" },
  { label: "fechado", category: "Valores" },
  { label: "desconectado", category: "Valores" },
  { label: "inautêntico", category: "Valores" },
  { label: "indiferente", category: "Valores" },
];

export const FUTURE_ADJECTIVES: AdjectiveItem[] = [
  // Emocional
  { label: "calmo", category: "Emocional" },
  { label: "sereno", category: "Emocional" },
  { label: "alegre", category: "Emocional" },
  { label: "equilibrado", category: "Emocional" },
  { label: "resiliente", category: "Emocional" },
  { label: "confiante", category: "Emocional" },
  { label: "compassivo", category: "Emocional" },
  { label: "grato", category: "Emocional" },
  { label: "leve", category: "Emocional" },
  { label: "inteiro", category: "Emocional" },
  { label: "amoroso", category: "Emocional" },
  { label: "forte", category: "Emocional" },
  // Cognitivo
  { label: "positivo", category: "Cognitivo" },
  { label: "flexível", category: "Cognitivo" },
  { label: "criativo", category: "Cognitivo" },
  { label: "focado", category: "Cognitivo" },
  { label: "racional", category: "Cognitivo" },
  { label: "consciente", category: "Cognitivo" },
  { label: "curioso", category: "Cognitivo" },
  { label: "claro", category: "Cognitivo" },
  { label: "presente", category: "Cognitivo" },
  { label: "decidido", category: "Cognitivo" },
  { label: "analítico", category: "Cognitivo" },
  { label: "expansivo", category: "Cognitivo" },
  // Social
  { label: "aberto", category: "Social" },
  { label: "empático", category: "Social" },
  { label: "generoso", category: "Social" },
  { label: "autônomo", category: "Social" },
  { label: "assertivo", category: "Social" },
  { label: "confiante", category: "Social" },
  { label: "presente", category: "Social" },
  { label: "acolhedor", category: "Social" },
  { label: "parceiro", category: "Social" },
  { label: "conectado", category: "Social" },
  { label: "respeitoso", category: "Social" },
  { label: "colaborativo", category: "Social" },
  // Comportamental
  { label: "ativo", category: "Comportamental" },
  { label: "determinado", category: "Comportamental" },
  { label: "protagonista", category: "Comportamental" },
  { label: "corajoso", category: "Comportamental" },
  { label: "disciplinado", category: "Comportamental" },
  { label: "organizado", category: "Comportamental" },
  { label: "consistente", category: "Comportamental" },
  { label: "realizador", category: "Comportamental" },
  { label: "proativo", category: "Comportamental" },
  { label: "crescendo", category: "Comportamental" },
  { label: "livre", category: "Comportamental" },
  { label: "intencional", category: "Comportamental" },
  // Valores
  { label: "autêntico", category: "Valores" },
  { label: "propositado", category: "Valores" },
  { label: "íntegro", category: "Valores" },
  { label: "sábio", category: "Valores" },
  { label: "justo", category: "Valores" },
  { label: "comprometido", category: "Valores" },
  { label: "solidário", category: "Valores" },
  { label: "transcendente", category: "Valores" },
  { label: "genuíno", category: "Valores" },
  { label: "inspirador", category: "Valores" },
  { label: "sustentável", category: "Valores" },
  { label: "pleno", category: "Valores" },
];
